### ISSUE TITLE
Bad contrast on matching brackets

### ISSUE THREAD

**Issue by rumpelsepp** [rakr/vim-one#17]
This theme suffers from excactly the same issue as I described here:

https://github.com/mhartington/oceanic-next/issues/20

**Comment by rakr** [comment]
Hi @rumpelsepp,

Updated the colorscheme a4b20dbe8129f66001cb0e26b98adeaf6959b6a8
Can you please have a look?

**Comment by rumpelsepp** [comment]
Sry for the delay. It is not fixed yet. I will provide a gif to illustrate the issue.

**Comment by numbcoder** [comment]
It is not fixed yet. When the cursor is placed on matching brackets,  the cursor blinking off

> When the cursor is placed on a bracket, it is very confusing since one cannot distinguish between the actual position of the cursor and the highlighted matched bracket.

**Comment by rakr** [comment]
Just pushed an update to prevent this behaviour
<img width="165" alt="1__vim-one__nvim__nvim_" src="https://cloud.githubusercontent.com/assets/110558/20877112/826b61d4-bb1a-11e6-8803-85efc33a118a.png">
<img width="151" alt="onedark_vim____workspaces_development_onedark_vim_colors__-_vim" src="https://cloud.githubusercontent.com/assets/110558/20877128/93ad2b1c-bb1a-11e6-90d0-faea70e73662.png">

r

**Comment by numbcoder** [comment]
:shipit:

**Comment by numbcoder** [comment]
Did you have pushed the update to github?

**Comment by numbcoder** [comment]
There is no update in github? Do I miss something?

**Comment by rakr** [comment]
No, I missed something (just a push :)
Sorry for the inconvenience.

**Comment by numbcoder** [comment]
Fixed! 💯 
Thank you!

**Comment by rumpelsepp** [comment]
@rakr It is unfortunately not yet fixed, see this gif here:

![out](https://cloud.githubusercontent.com/assets/1961699/20966976/4dd852ba-bc7d-11e6-83f6-56ded2be793b.gif)

**Comment by rumpelsepp** [comment]
finally this is fixed now! thanks!
