### ISSUE TITLE
terminal: doesn't work with limelight: need g:limelight_conceal_ctermfg

### ISSUE THREAD

**Issue by gauteh** [rakr/vim-one#65]
This is probably not your problem, but I wanted to point out that this scheme (dark/light) in terminal does not work with the limelight plugin: https://github.com/junegunn/limelight.vim#options

I get the error:  ` g:limelight_conceal_ctermfg required.` when trying to turn limelight on.

**Comment by dkarter** [comment]
@gauteh I am not experiencing the same issue - perhaps it was fixed already... If you do need to set those you can do that yourself like so

```vim
  let g:limelight_conceal_ctermfg = '#454d5a'
  let g:limelight_conceal_guifg = '#454d5a'
```

Just add these two lines to your vimrc.

**Comment by gauteh** [comment]
Dorian Karter writes on januar 7, 2018 23:54:
> @gauteh I am not experiencing the same issue - perhaps it was fixed already... If you do need to set those you can do that yourself like so
> 
> ```vim
>   let g:limelight_conceal_ctermfg = '#454d5a'
>   let g:limelight_conceal_guifg = '#454d5a'
> ```
> 
> Just add these two lines to your vimrc.

Thanks, that should do the trick. I updated my plugins / colorschemes 
and still the same (in terminal at least).
